name: delivery_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.16
  firebase_core: ^1.15.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  google_fonts: ^2.3.1
  mask_text_input_formatter: ^2.3.0
  pin_code_fields: ^7.4.0
  flutter_svg: ^1.0.3
  get: ^4.3.8
  cloud_firestore: ^3.1.15



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.6

flutter_native_splash:
  color: "#ffffff"
  image: assets/png/logo_splash_screen.png

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/

